version: "3"

services:
  nginx:
    build:
      context: server/nginx
    container_name: badgerherald.com-nginx
    links:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - badgerherald.com-wordpress:/var/www/html
      - ./${WORDPRESS_UPLOADS_DIR}:/var/www/html/wp-content/uploads
    restart: always
    environment: 
      DOMAIN: ${SITE_URL}

  wordpress:
    container_name: badgerherald.com-wordpress
    build:
      context: .
    links:
      - memcached
    expose:
      - 80
    restart: always
    volumes:
      - badgerherald.com-wordpress:/var/www/html
      - ./${WORDPRESS_UPLOADS_DIR}:/var/www/html/wp-content/uploads
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes/badgerherald.com:/var/www/html/wp-content/themes/badgerherald.com
      - ./server/wordpress/php.ini:/usr/local/etc/php/conf.d/extra.ini
      - ./server/wordpress/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-my-extra.conf
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        /* Domain */
        define('WP_HOME','https://${SITE_URL}');
        define('WP_SITEURL','https://${SITE_URL}');
        define('EXA_DEV','false');
        define('WP_CACHE',true);
        define('WP_MEMORY_LIMIT','128M');
        $$memcached_servers = array(
          'default' => array(
            'memcached:11211',
          )
        );
        include(wp-config-2.php);

  memcached:
    container_name: badgerherald.com-memcached
    image: memcached:latest
    ports:
      - "11211:11211"

  mariadb:
    container_name: badgerherald.com-mariadb
    image: mariadb
    volumes:
      - ./server/sql/install/:/docker-entrypoint-initdb.d
      - badgerherald.com-mariadb:/var/lib/mysql:rw
      - ./server/MySQLTuner-perl/:/MySQLTuner-perl/
    restart: always
    command: mysqld --innodb-buffer-pool-size=512M
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}

volumes:
  badgerherald.com-mariadb:
  badgerherald.com-wordpress:

networks:
  default:
    external:
      name: badgerherald.com-network
    